version: '3.7'

services: 
    db:
        image: mysql:5.7
        restart: always
        volumes:
            - "./db:/var/lib/mysql"
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_ROOT_USERNAME
        networks: 
            - app

networks:
    app:
        driver: bridge